// Generated by scripts/intl-profile.py --write; do not edit.
// Locked ICU dependency graph (versions, checksums, edges and root features).
// SHA-256: 8c77b93d00a20b90d248b50a25a3ee4f662cb83e55981a3633a37472defdd33c
pub(crate) const INTL_DATA_VERSION: &str = "ironhorse-intl-2026a";
