export type * from './src/types.js';
export type { GitOperations } from './src/git.js';
export {
  makeGit,
  makeGitKit,
  makeGitOperations,
  isGitHistoryRewrite,
  isGitReadOnly,
  makeNotYetImplementedBackend,
  makeGitFsBackend,
  makeGitRemoteEndpoint,
  makeGitRemote,
  normalizeGitRemotePolicy,
  makeGitCloner,
  getGitRemoteController,
  makeBasicCredential,
  makeBearerCredential,
  makeUnavailableGitCredential,
  assertGitCredentialForUrl,
  revokeGitCredential,
  getGitCredentialController,
  GitInterface,
  GitReaderInterface,
  GitWriterInterface,
  GitRewriterInterface,
  GitTreeInterface,
  GitRemoteInterface,
  GitRemoteControllerInterface,
  GitCredentialControllerInterface,
  BasicCredentialInterface,
  BearerCredentialInterface,
} from './src/index.js';
