// skiplists.mjs — the a-priori filter tables, ported VERBATIM from the persona's sweep.py + rank.py.
// These encode "which cuisines/venues are categorically wrong for a histamine/MCAS/fructan diet" so the
// expensive per-restaurant LLM eval is only spent on plausible candidates. Two tiers:
//   AUTO_SKIP      — keyed by Google Places `primaryType` (the structured signal).
//   NAME_AUTO_SKIP — case-insensitive regexes against the display name (catches what the type misses).
// PRIORITY ranks the survivors by how likely the cuisine is to have an orderable safe dish (rank.py).
//
// Plain node (no Endo/harden) so the pipeline is headless-testable; grunt.mjs hardens at the cap boundary.

// primaryType → human reason (≈70 entries). Ported 1:1 from sweep.py AUTO_SKIP.
export const AUTO_SKIP = {
  thai_restaurant: 'Thai — fish sauce + garlic/onion baseline',
  vietnamese_restaurant: 'Vietnamese — fish sauce, pickled aromatics',
  korean_restaurant: 'Korean — fermented (kimchi, gochujang, doenjang)',
  ramen_restaurant: 'Ramen — long-simmered broth with aromatics + fermented',
  sushi_restaurant: 'Sushi — raw fish histamine + soy sauce',
  indian_restaurant: 'Indian — onion/garlic base + fermented elements',
  pakistani_restaurant: 'Pakistani — onion/garlic base',
  italian_restaurant: 'Italian — tomato + aged cheese + cured meats',
  pizza_restaurant: 'Pizza — tomato + aged cheese + wheat',
  mexican_restaurant: 'Mexican — onion-heavy + cheese',
  taco_restaurant: 'Taco — onion + tomato + cheese typical',
  burrito_restaurant: 'Burrito — onion + cheese + tomato',
  chinese_restaurant: 'Chinese — soy sauce + fermented bean pastes baseline',
  dim_sum_restaurant: 'Dim sum — soy + fermented',
  ramen: 'Ramen — long-simmered broth',
  bar: 'Bar — alcohol-forward; aged cheese / charcuterie typical',
  night_club: 'Night club — alcohol-forward',
  brewery: 'Brewery — alcohol + fermented',
  pub: 'Pub — alcohol-forward',
  wine_bar: 'Wine bar — alcohol + aged cheese',
  bakery: 'Bakery — wheat + sugar-heavy',
  dessert_restaurant: 'Dessert — sugar-forward',
  ice_cream_shop: 'Ice cream — dessert',
  donut_shop: 'Donut — wheat + sugar',
  candy_store: 'Candy — not a meal',
  chocolate_shop: 'Chocolate — Alexa avoids chocolate',
  buffet_restaurant: 'Buffet — food sits, histamine accumulation',
  chicken_wing_restaurant: 'Wings — sauced, usually fried',
  middle_eastern_restaurant: 'Middle Eastern — onion/garlic base, tahini/yogurt heavy',
  lebanese_restaurant: 'Lebanese — onion/garlic base, tahini',
  turkish_restaurant: 'Turkish — onion/garlic base',
  afghani_restaurant: 'Afghani — similar Middle Eastern profile',
  persian_restaurant: 'Persian — onion/garlic base',
  caribbean_restaurant: 'Caribbean — slow-simmered, spiced, soy',
  jamaican_restaurant: 'Jamaican — jerk = chili + soy + allspice',
  ethiopian_restaurant: 'Ethiopian — fermented injera + berbere',
  deli: 'Deli — cured meats + aged cheeses default',
  sandwich_shop: 'Sandwich — cured meats + aged cheese default',
  bagel_shop: 'Bagel — wheat-heavy',
  coffee_shop: 'Coffee — not a meal venue',
  cafe: 'Cafe — typically wheat/sugar/coffee focus',
  juice_shop: 'Juice — not a meal venue',
  smoothie_shop: 'Smoothie — typically fruit + dairy',
  tea_house: 'Tea — not a meal venue',
  fast_food_restaurant: 'Fast food — processed, not cook-to-order',
  spanish_restaurant: 'Spanish — cured meats + aged cheese + tomato',
  tapas_restaurant: 'Tapas — cured meats, aged cheese',
  tapas_bar: 'Tapas — cured meats, aged cheese',
  chinese_noodle_restaurant: 'Chinese noodles — soy/fermented',
  asian_restaurant: 'Generic Asian — typically soy/fermented base',
  cajun_restaurant: 'Cajun — spicy + often shellfish',
  oyster_bar_restaurant: 'Oyster bar — shellfish hard avoid',
  barbecue_restaurant: 'BBQ — sauced, smoked (histamine)',
  soul_food_restaurant: 'Soul food — fried + slow-cooked',
  beer_garden: 'Beer garden — alcohol-forward',
  latin_american_restaurant: 'Latin American — typically tomato/cheese/spice base',
  hamburger_restaurant: 'Hamburger — onion/cheese/tomato default',
  chicken_restaurant: 'Chicken chain — typically marinated/sauced',
  chicken_wings_restaurant: 'Wings — sauced/fried',
  market: 'Market — not a sit-down restaurant',
  grocery_store: 'Grocery — not a restaurant',
  supermarket: 'Supermarket — not a restaurant',
  food_court: 'Food court — varied/unverified components',
  meal_takeaway: 'Generic takeaway',
  meal_delivery: 'Generic delivery',
  fish_and_chips_restaurant: 'Fish & chips — fried/batter',
  fusion_restaurant: 'Fusion — typically fermented umami bases',
  vegan_restaurant: 'Vegan — typically fermented umami / many hard avoids',
  vegetarian_restaurant: 'Vegetarian — often fermented umami / legume-heavy',
};

// [regex, reason] — matched against the display name. Ported 1:1 from sweep.py NAME_AUTO_SKIP
// (Python re.I → JS /i; the patterns are JS-regex-compatible as written). First match wins.
export const NAME_AUTO_SKIP = [
  [/\bsushi\b/i, 'Sushi — raw fish histamine + soy'],
  [/\bhandroll\b/i, 'Handroll/sushi — raw fish'],
  [/\bomakase\b/i, 'Omakase/sushi — raw fish'],
  [/\bpho\b/i, 'Pho — Vietnamese, fish sauce'],
  [/\bramen\b/i, 'Ramen — long-simmered broth'],
  [/\bteriyaki\b/i, 'Teriyaki — soy + sugar + garlic'],
  [/\bhawaiian\s+(bbq|barbecue)\b/i, 'Hawaiian BBQ — teriyaki/marinade-heavy (pattern verified across multiple evals)'],
  [/\bbbq\s+hawaiian\b/i, 'Hawaiian BBQ — teriyaki/marinade'],
  [/\bdrive[\s-]?inn?\b/i, 'Drive-in (typically Hawaiian BBQ chain)'],
  [/\bhot chicken\b/i, 'Hot chicken — spicy + sauced'],
  [/\bdumpling/i, 'Dumplings — soy sauce, sometimes pickled fillings'],
  [/\bbiryani\b/i, 'Biryani — Indian'],
  [/\bkebab/i, 'Kebab — typically Middle Eastern marinades'],
  [/\bshawarma/i, 'Shawarma — marinated'],
  [/\bfalafel\b/i, 'Falafel — chickpeas (FODMAP), garlic, tahini'],
  [/\bhummus/i, 'Hummus-focused — chickpeas/tahini/garlic'],
  [/\bcurry\b/i, 'Curry — onion/garlic + fermented'],
  [/\bdim sum\b/i, 'Dim sum — soy/fermented'],
  [/\bvegan\b/i, 'Vegan — typically relies on fermented umami / many hard avoids'],
  [/\bdeli(\b|catessen)/i, 'Deli — cured meats + aged cheese default'],
  [/\bsandwich(es|)\b/i, 'Sandwich shop — cured meats default'],
  [/\bwings?\b/i, 'Wings — sauced/fried'],
  [/\bnoodle (house|bar|shop)\b/i, 'Noodle shop — soy/fermented'],
  [/\btacos?\b/i, 'Tacos — onion/tomato/cheese default'],
  [/\bburrito\b/i, 'Burrito — onion/cheese/tomato'],
  [/\bbagel/i, 'Bagel — wheat-heavy'],
  [/\bdonut/i, 'Donut — wheat + sugar'],
  [/\bice cream\b/i, 'Ice cream — dessert'],
  [/\bcoffee\b|\bespresso\b/i, 'Coffee — not a meal venue'],
  [/\bjuice\b/i, 'Juice — not a meal venue'],
  [/\bsmoothie\b/i, 'Smoothie — fruit + dairy'],
  [/\bboba\b|\bbubble tea\b/i, 'Boba — sugar + dairy'],
  [/\bfish\s*&?\s*chips\b/i, 'Fish & chips — fried, batter'],
  [/\boyster/i, 'Oyster — shellfish hard avoid'],
  [/\bcrab(\b|s\b|\s)/i, 'Crab — shellfish'],
  [/\blobster/i, 'Lobster — shellfish'],
  [/\bshrimp/i, 'Shrimp — shellfish'],
  [/\bcatering\b/i, 'Catering service — not a lunch venue'],
  [/\b(market|grocery|supermarket)\b/i, 'Market/grocery — not a restaurant'],
  [/\bboil\b/i, 'Seafood boil — shellfish + spice'],
  [/\bpub\b/i, 'Pub — alcohol-focused'],
  [/\btavern\b/i, 'Tavern — alcohol-focused'],
  [/\bbrew/i, 'Brewery/brewpub — alcohol + fermented'],
  [/\blounge\b/i, 'Lounge — alcohol-focused'],
  [/\bwaffle/i, 'Waffle — wheat + sugar'],
  [/\bpancake/i, 'Pancake — wheat + sugar'],
  [/\bbakery\b/i, 'Bakery — wheat-heavy'],
  [/\bcheese(s|)\b/i, 'Cheese-focused — aged cheese hard avoid'],
  [/\bchocolate/i, 'Chocolate — Alexa avoids chocolate'],
];

// primaryType → priority score (higher = more likely to have a safe orderable dish). rank.py PRIORITY.
export const PRIORITY = {
  steak_house: 10,
  mediterranean_restaurant: 9,
  greek_restaurant: 9,
  brazilian_restaurant: 8,
  californian_restaurant: 7,
  seafood_restaurant: 7,
  brunch_restaurant: 6,
  breakfast_restaurant: 6,
  diner: 6,
  health_food_restaurant: 6,
  salad_shop: 5,
  american_restaurant: 4,
  japanese_restaurant: 4,
  hawaiian_restaurant: 3,
  soup_restaurant: 3,
  restaurant: 2,
  food: 1,
};

// the priority of a candidate's primaryType (default 1), per rank.py rank().
export const priorityOf = primaryType => PRIORITY[primaryType] ?? 1;
