//! Compartment-mapper fixture-parity harness for the `endor run
//! <entry.js>` dependency walker (`entry_walk::ingest_entry_point_with_deps`).
//!
//! This crate reimplements a slice of `@endo/compartment-mapper`:
//! the node_modules dependency walk that turns an ES-module entry
//! point into a multi-compartment archive. To establish — and keep
//! honest — parity with the reference implementation, this harness
//! accounts for **every** fixture directory under
//! `packages/compartment-mapper/test`, the same tree the
//! compartment-mapper's own ava suite consumes.
//!
//! It is the substrate for the **fixture-parity ratchet**
//! (`designs/endor-run-expanded.md` § Fixture-parity ratchet): a monotonic campaign
//! from 7-of-40 exercised toward full parity between endor's walker
//! and node's `@endo/compartment-mapper`, capability by capability.
//! Four mechanisms keep the ratchet drift-proof:
//!
//! 1. **Two-tier exclusions.** A non-exercised fixture is either a
//!    [`Disposition::PendingExclude`] (blocked on a named walker
//!    capability that a later increment will land — it *will*
//!    graduate) or a [`Disposition::DurableExclude`] (a
//!    compartment-mapper-internal concern out of the walker's scope —
//!    it will not). The [`scoreboard`] test reports `exercised /
//!    pending / durable`, making campaign progress a measurable number.
//!
//! 2. **No silent drift.** A `fixtures-*` directory on disk but absent
//!    from [`MANIFEST`] — or a manifest entry with no directory —
//!    fails [`no_unaccounted_fixture_drift`]. A newly added fixture
//!    cannot be silently ignored; whoever adds one decides, on the
//!    record, whether it is in scope.
//!
//! 3. **Exercised floor (anti-backslide).** [`EXERCISED_FLOOR`] is a
//!    hard, ratcheting minimum. Each increment that graduates fixtures
//!    raises it; a later change that silently re-excludes a graduated
//!    fixture drops below the floor and fails the suite.
//!
//! 4. **Parity asserted against node, structurally.** An exercised
//!    fixture is no longer checked by a hand-written compartment
//!    *count*. Instead the walker's output is projected to a stable
//!    structural shape (compartment names, per-compartment module
//!    specifiers, and the parser language per module) and diffed
//!    against a committed golden generated by the harness-free node
//!    reference oracle (`rust/endo/tools/gen-parity-golden.mjs`), which
//!    imports `@endo/compartment-mapper` directly. See
//!    [`exercised_fixtures_match_node_golden`].
//!
//! When the walker grows a capability (CommonJS `require`, conditional
//! `exports`, dynamic `import()`, …), the corresponding fixtures move
//! from a `*Exclude` to [`Disposition::Exercise`] here **in the same
//! commit** that lands the capability and commits the fixture's golden,
//! and the floor is bumped. No fixtures graduate in this increment
//! (Increment 0): it lands the oracle, the golden diff, the two-tier
//! split, the floor, and the scoreboard.
//!
//! Per the job that established this harness, the fixtures stay where
//! they live today, under `packages/compartment-mapper/test`; hoisting
//! them into a shared top-level `test/fixtures` tree (as the test262
//! fixtures are arranged) is a deliberately separate, later question.

use endo::cas::ContentStore;
use endo::entry_walk::{
    ingest_entry_point_with_deps, ingest_entry_point_with_deps_with_options, ModuleSourceOrigin,
    SyntheticModuleSource, WalkOptions,
};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

/// What the parity harness does with one fixture directory.
enum Disposition {
    /// The walker is run against `entry` (a path relative to the
    /// fixture directory) and its compartment map is diffed,
    /// structurally, against the committed golden at
    /// `<fixture>/expected-compartment-map.json` (see
    /// [`exercised_fixtures_match_node_golden`]). Reserved for
    /// fixtures whose reachable graph is expressible through the
    /// walker's supported resolution: static ES `import` / `export …
    /// from`, relative specifiers with the extension/`index`
    /// fall-back, and bare specifiers resolved via `node_modules` with
    /// the `exports["."]` default-string / `main` / `index` cascade.
    Exercise { entry: &'static str },
    /// The walker does not *yet* handle this fixture, but a later
    /// ratchet increment will: `capability` names the walker
    /// capability group (see `designs/endor-run-expanded.md`
    /// § Fixture-parity ratchet) it is blocked on. These shrink toward zero as the campaign
    /// advances — they are the campaign's work queue.
    #[allow(dead_code)] // Kept as the required classification for future fixture drift.
    PendingExclude { capability: &'static str },
    /// The fixture exercises a compartment-mapper-*internal* concern
    /// (a naming strategy, a policy engine, a strict-mode diagnostic, a
    /// deliberate error) that is out of scope for a dependency-walk
    /// parity harness; `reason` says why. These are not chased — they
    /// are the campaign's horizon (`designs/…` §3).
    DurableExclude { reason: &'static str },
}

use Disposition::{DurableExclude, Exercise, PendingExclude};

/// The hard, ratcheting minimum number of exercised fixtures. Increment
/// 0 established the baseline at 7; Increment 1 (CommonJS `require()`,
/// Group A) graduated `cjs-compat`, `cycle-cjs`, `digest`, and
/// `esm-imports-cjs-define`, raising it to 11; Increment 2 (conditional
/// & subpath `exports`/`#imports`, Group C) graduates
/// `conditional-host-exports`, `export-patterns`,
/// `package-imports-exports`, `nested-pkg`, and the mixed CJS/ESM
/// kitchen-sink `fixtures-0`, raising it to 16. Increment 3
/// (dev/peer/optional dependency classification, Group D)
/// graduates `no-trans-dev-deps`,
/// `missing-optional-peer-dependencies`, and
/// `optional-peer-dependencies`, raising it to 19. Increment 4 (dynamic
/// `import()`/`require()`, Group B) graduates `dynamic`,
/// `dynamic-ancestor`, `dynamic-import-esm`, and `optional`, raising it
/// to 23. Increment 5 (nested/duplicate/symlink/resolve resolution,
/// Group G) graduates `fixtures-1`, `stability`, `common-deps`,
/// `symlink`, and `resolve`, raising it to 28. Increment 6
/// (language-for-extension & non-JS assets, Group E) graduates `assets`
/// (default `text`/`bytes` languages plus the entry package's
/// `parsers: { uint32: bytes }`) and `language-for-extension` (the emulated
/// `languageForExtension: { xsonp: jsonp }`), raising it to 30. Increment 7
/// (host hooks, Group F) graduates `exit` and `module-source-hook` through
/// emulated exit-module and module-source hooks, raising it to 32. Each later
/// increment raises it further (per `designs/endor-run-expanded.md`
/// § Fixture-parity ratchet). A
/// change that silently re-excludes a graduated fixture drops below this
/// floor and fails [`exercised_fixtures_match_node_golden`].
///
/// Increment 8 restores `dynamic-import-esm` after the walker learned to retain
/// every declared runtime dependency that an opaque `import(specifier)` may
/// name, returning the ratchet to 32 exercised fixtures.
const EXERCISED_FLOOR: usize = 32;

/// Every `fixtures-*` directory under
/// `packages/compartment-mapper/test`, each accounted for exactly
/// once. Kept in directory-name order.
///
/// INVARIANT: this list is the complete, exact set of `fixtures-*`
/// directories. The `no_unaccounted_fixture_drift` test enforces it
/// against the real tree in both directions.
const MANIFEST: &[(&str, Disposition)] = &[
    (
        "fixtures-0",
        Exercise {
            entry: "node_modules/app/main.js",
        },
    ),
    (
        "fixtures-1",
        Exercise {
            entry: "node_modules/evan/index.js",
        },
    ),
    (
        "fixtures-assets",
        Exercise { entry: "main.js" },
    ),
    (
        "fixtures-cjs-compat",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-common-deps",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-conditional-host-exports",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    ("fixtures-cthuloops", Exercise { entry: "main.js" }),
    (
        "fixtures-cycle-cjs",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-cycle-mjs",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-digest",
        Exercise {
            entry: "node_modules/app2/index.js",
        },
    ),
    (
        "fixtures-dynamic",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-dynamic-ancestor",
        Exercise {
            entry: "node_modules/webpackish-app/build.js",
        },
    ),
    (
        "fixtures-dynamic-import-esm",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-error-handling",
        DurableExclude {
            reason: "negative fixture: deliberate resolution/parse error injection to exercise compartment-mapper diagnostics; parity here means matching an error, a different assertion kind out of the walker's scope",
        },
    ),
    (
        "fixtures-esm-imports-cjs-define",
        Exercise { entry: "0.mjs" },
    ),
    (
        "fixtures-exit",
        Exercise {
            entry: "import-export.js",
        },
    ),
    (
        "fixtures-export-patterns",
        Exercise {
            entry: "node_modules/app/main.js",
        },
    ),
    ("fixtures-implicit-reexport", Exercise { entry: "index.js" }),
    (
        "fixtures-language-for-extension",
        Exercise {
            entry: "node_modules/module-app/module.xsonp",
        },
    ),
    (
        "fixtures-missing-optional-peer-dependencies",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-module-source-hook",
        Exercise {
            entry: "node_modules/app-implicit/index.js",
        },
    ),
    (
        "fixtures-nested-pkg",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-no-name",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-no-trans-dev-deps",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    (
        "fixtures-noble",
        DurableExclude {
            reason: "compartment-mapper-internal: conditional exports plus require()-based deps combined with a policy/naming strategy that is not a walker concern",
        },
    ),
    (
        "fixtures-optional",
        Exercise {
            entry: "node_modules/optional-esm/index.js",
        },
    ),
    (
        "fixtures-optional-peer-dependencies",
        Exercise {
            entry: "node_modules/app/index.js",
        },
    ),
    ("fixtures-order", Exercise { entry: "index.js" }),
    (
        "fixtures-package-imports-exports",
        Exercise {
            entry: "node_modules/app/main.js",
        },
    ),
    (
        "fixtures-policy",
        DurableExclude {
            reason: "compartment-mapper-internal: policy enforcement (an attenuation/permission engine) is not a dependency-ingestion concern",
        },
    ),
    (
        "fixtures-resolve",
        Exercise {
            entry: "node_modules/browser/main.js",
        },
    ),
    (
        "fixtures-retained",
        DurableExclude {
            reason: "compartment-mapper-internal: retained-modules (retention across the graph) is a compartment-mapper-specific flag, not a walker concern",
        },
    ),
    (
        "fixtures-shortest-path",
        DurableExclude {
            reason: "compartment-mapper-internal: shortest-path compartment naming strategy over a require()-based graph is not a walker concern",
        },
    ),
    (
        "fixtures-shortest-path-cycle",
        DurableExclude {
            reason: "compartment-mapper-internal: shortest-path naming with a require()-based cycle is a naming strategy, not a walker concern",
        },
    ),
    (
        "fixtures-stability",
        Exercise { entry: "a.js" },
    ),
    ("fixtures-stack", Exercise { entry: "index.js" }),
    (
        "fixtures-strict",
        Exercise {
            entry: "node_modules/app/main.js",
        },
    ),
    (
        "fixtures-strictly-inconsistent-directories",
        DurableExclude {
            reason: "compartment-mapper-internal: strict-mode directory-inconsistency diagnostic is a compartment-mapper-specific check, not a walker concern",
        },
    ),
    (
        "fixtures-strictly-inconsistent-packages",
        DurableExclude {
            reason: "compartment-mapper-internal: strict-mode package-inconsistency diagnostic is a compartment-mapper-specific check, not a walker concern",
        },
    ),
    (
        "fixtures-symlink",
        Exercise {
            entry: "app/index.js",
        },
    ),
];

/// Absolute path to `packages/compartment-mapper/test`, resolved from
/// this crate's manifest directory (`rust/endo`).
fn fixtures_root() -> PathBuf {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/compartment-mapper/test");
    root.canonicalize().unwrap_or_else(|e| {
        panic!(
            "compartment-mapper fixtures directory not found at {}: {e}. \
             This parity harness expects the fixtures in place under \
             packages/compartment-mapper/test.",
            root.display()
        )
    })
}

/// The `fixtures-*` directory names actually present on disk.
fn on_disk_fixture_dirs(root: &Path) -> BTreeSet<String> {
    std::fs::read_dir(root)
        .unwrap_or_else(|e| panic!("cannot read fixtures root {}: {e}", root.display()))
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.path().is_dir())
        .filter_map(|entry| entry.file_name().into_string().ok())
        .filter(|name| name.starts_with("fixtures-"))
        .collect()
}

/// The `fixtures-*` directory names accounted for in [`MANIFEST`].
fn manifest_fixture_dirs() -> BTreeSet<String> {
    MANIFEST.iter().map(|(name, _)| name.to_string()).collect()
}

// Structural projection & golden diff
//
// The parity comparison is made on a *projection* of the compartment
// map, not its raw form, under two canonicalisations that both this
// harness and the node oracle apply identically (see
// `rust/endo/tools/gen-parity-golden.mjs` for the authoritative prose):
//
//   1. Compartments are keyed by `name`, not the version-suffixed
//      `<name>-v<version>` id (endor defaults an absent version to
//      0.0.0, compartment-mapper leaves it empty; version-string
//      parity is out of the walker's scope).
//   2. A module whose specifier ends in a bare `.js` records the
//      language family `"js"` rather than `mjs`/`cjs`, because the
//      mjs-vs-cjs classification of a `.js` file depends on the
//      package's `type` field, which endor's extension-only classifier
//      does not yet read. Unambiguous extensions keep their language.

/// One compartment's projected module table: specifier → `"lang:<x>"`
/// for a file module, or `"link:<targetCompartmentName>"` for a
/// cross-compartment (or self) link. Ordered for a stable diff.
type ProjectedCompartment = BTreeMap<String, String>;

/// A projected compartment map: entry (compartment name, module
/// specifier) plus compartment-name → module table.
struct Projected {
    entry_compartment: String,
    entry_module: String,
    compartments: BTreeMap<String, ProjectedCompartment>,
}

#[derive(Debug, Default, PartialEq, Eq)]
struct ExpectedHooks {
    exit_module_imports: Vec<String>,
    module_sources: Vec<(String, String)>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Projection {
    /// Full archive projection: file languages, links, exits, and deferred
    /// errors.
    Archive,
    /// The package classifier's stable surface: compartment identities and
    /// cross-compartment dependency links. Group D uses this for deliberately
    /// excluded source edges; Group B uses it where dynamic package edges are
    /// not represented completely in the archive map. The node oracle is
    /// `mapNodeModules` itself for these fixtures.
    DependencyClassification,
    /// Archive projection for Group F's emulated host hooks. Node keeps an
    /// exit-hook record outside the archive and resolves it when importing;
    /// endor materializes equivalent source in the CAS. The synthetic file is
    /// therefore omitted from the structural map while hook invocations and
    /// real execution are asserted separately.
    ArchiveHostHooks,
}

/// The projected compartment key: the package `name` plus any
/// duplicate-copy disambiguation suffix (`-n1`, `-n2`, …) carried by the
/// compartment id. The version segment (`-v<version>`) is dropped —
/// endor defaults an absent version to `0.0.0` while compartment-mapper
/// leaves it empty, and version-string parity is out of the walker's
/// scope (rule 1) — but the `-n<k>` disambiguator IS part of the graph's
/// identity for a fixture with duplicate name/version copies
/// (`fixtures-stability`, `fixtures-1`), so it is preserved. The
/// disambiguator is always the id's trailing `-n<digits>` (it is appended
/// last by both engines); a package `name`/`version` that itself ends in
/// `-n<digits>` is out of scope for these fixtures.
fn projected_key(name: &str, id: &str) -> String {
    let unscoped = name.rsplit('/').next().unwrap_or(name);
    if let Some(pos) = id.rfind("-n") {
        let tail = &id[pos + 2..];
        if !tail.is_empty() && tail.bytes().all(|b| b.is_ascii_digit()) {
            return format!("{unscoped}{}", &id[pos..]);
        }
    }
    unscoped.to_string()
}

/// Normalise a parser tag + specifier to the canonical language (rule 2
/// above). `.js` ⇒ `"js"`; everything else keeps its base language.
fn canonical_language(parser: &str, specifier: &str) -> String {
    let base = match parser {
        "mjs" | "pre-mjs-json" => "mjs",
        "cjs" | "pre-cjs-json" => "cjs",
        "json" | "pre-json" => "json",
        other => other,
    };
    if specifier.ends_with(".js") && (base == "mjs" || base == "cjs") {
        "js".to_string()
    } else {
        base.to_string()
    }
}

/// Project endor's live compartment map into the comparison shape.
fn project_endor(map: &xsnap::archive::CompartmentMap, projection: Projection) -> Projected {
    use xsnap::archive::ModuleDescriptor::*;

    let id_to_key: BTreeMap<&str, String> = map
        .compartments
        .iter()
        .map(|(id, c)| (id.as_str(), projected_key(&c.name, id)))
        .collect();
    let key_of = |compartment_id: &str| -> String {
        id_to_key
            .get(compartment_id)
            .cloned()
            .unwrap_or_else(|| compartment_id.to_string())
    };

    let mut compartments = BTreeMap::new();
    for (id, c) in map.compartments.iter() {
        let self_key = key_of(id);
        let mut modules = ProjectedCompartment::new();
        for (spec, desc) in &c.modules {
            if projection == Projection::DependencyClassification {
                let Link { compartment, .. } = desc else {
                    continue;
                };
                let target = key_of(compartment);
                if target != self_key {
                    modules.insert(spec.clone(), format!("link:{target}"));
                }
                continue;
            }
            let value = match desc {
                File {
                    parser, location, ..
                } => {
                    if projection == Projection::ArchiveHostHooks
                        && location
                            .as_deref()
                            .is_some_and(|value| value.starts_with("__synthetic_"))
                    {
                        continue;
                    }
                    format!("lang:{}", canonical_language(parser, spec))
                }
                Link { compartment, .. } => {
                    format!("link:{}", key_of(compartment))
                }
                Exit { exit } => format!("exit:{exit}"),
                DeferredError { .. } => "deferredError".to_string(),
            };
            modules.insert(spec.clone(), value);
        }
        compartments.insert(self_key, modules);
    }

    let entry_compartment = key_of(map.entry.compartment.as_str());

    Projected {
        entry_compartment,
        entry_module: map.entry.module.clone(),
        compartments,
    }
}

/// Parse a committed golden JSON into the same comparison shape.
fn parse_golden(path: &Path) -> (Projection, Projected, ExpectedHooks) {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read golden {}: {e}", path.display()));
    let v: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("golden {} is not valid JSON: {e}", path.display()));

    let entry_compartment = v["entryCompartment"]
        .as_str()
        .unwrap_or_else(|| panic!("golden {} missing entryCompartment", path.display()))
        .to_string();
    let entry_module = v["entryModule"]
        .as_str()
        .unwrap_or_else(|| panic!("golden {} missing entryModule", path.display()))
        .to_string();

    let mut compartments = BTreeMap::new();
    let comp_obj = v["compartments"]
        .as_object()
        .unwrap_or_else(|| panic!("golden {} missing compartments object", path.display()));
    for (name, comp) in comp_obj {
        let mut modules = ProjectedCompartment::new();
        let mods = comp["modules"].as_object().unwrap_or_else(|| {
            panic!(
                "golden {} compartment {name} missing modules",
                path.display()
            )
        });
        for (spec, desc) in mods {
            let value = if let Some(lang) = desc["language"].as_str() {
                format!("lang:{lang}")
            } else if let Some(link) = desc["link"].as_str() {
                format!("link:{link}")
            } else if let Some(exit) = desc["exit"].as_str() {
                format!("exit:{exit}")
            } else if desc.get("deferredError").is_some() {
                "deferredError".to_string()
            } else {
                panic!(
                    "golden {} module {spec} has no recognised descriptor ({desc})",
                    path.display()
                )
            };
            modules.insert(spec.clone(), value);
        }
        compartments.insert(name.clone(), modules);
    }

    let projection = match v.get("projection").and_then(|value| value.as_str()) {
        Some("dependency-classification") => Projection::DependencyClassification,
        Some("archive-host-hooks") => Projection::ArchiveHostHooks,
        Some(other) => panic!("golden {} has unknown projection {other:?}", path.display()),
        None => Projection::Archive,
    };

    let expected_hooks = if let Some(hooks) = v.get("emulatedHooks") {
        let exit_module_imports = hooks["exitModuleImports"]
            .as_array()
            .unwrap_or_else(|| {
                panic!(
                    "golden {} emulatedHooks.exitModuleImports is not an array",
                    path.display()
                )
            })
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .unwrap_or_else(|| {
                        panic!(
                            "golden {} has a non-string exit-module observation",
                            path.display()
                        )
                    })
                    .to_string()
            })
            .collect();
        let module_sources = hooks["moduleSources"]
            .as_array()
            .unwrap_or_else(|| {
                panic!(
                    "golden {} emulatedHooks.moduleSources is not an array",
                    path.display()
                )
            })
            .iter()
            .map(|value| {
                let origin = value["origin"].as_str().unwrap_or_else(|| {
                    panic!(
                        "golden {} has a module-source observation without an origin",
                        path.display()
                    )
                });
                let specifier = value["specifier"].as_str().unwrap_or_else(|| {
                    panic!(
                        "golden {} has a module-source observation without a specifier",
                        path.display()
                    )
                });
                (origin.to_string(), specifier.to_string())
            })
            .collect();
        ExpectedHooks {
            exit_module_imports,
            module_sources,
        }
    } else {
        ExpectedHooks::default()
    };

    (
        projection,
        Projected {
            entry_compartment,
            entry_module,
            compartments,
        },
        expected_hooks,
    )
}

/// Human-readable one-line rendering of a projected map, for diffs.
fn render(p: &Projected) -> String {
    let mut s = format!("entry {}::{}\n", p.entry_compartment, p.entry_module);
    for (name, mods) in &p.compartments {
        s.push_str(&format!("  compartment {name}\n"));
        for (spec, value) in mods {
            s.push_str(&format!("    {spec} => {value}\n"));
        }
    }
    s
}

// Tests

/// The drift safeguard. A fixture on disk but not in [`MANIFEST`] —
/// or a [`MANIFEST`] entry with no directory on disk — fails here, so
/// no fixture can be silently added or removed without a maintainer
/// deciding, on the record, whether it is in scope for the walker.
#[test]
fn no_unaccounted_fixture_drift() {
    let root = fixtures_root();
    let on_disk = on_disk_fixture_dirs(&root);
    let manifest = manifest_fixture_dirs();

    // No fixture may appear twice in the manifest.
    assert_eq!(
        manifest.len(),
        MANIFEST.len(),
        "MANIFEST contains duplicate fixture entries: {:?}",
        {
            let mut seen = BTreeSet::new();
            MANIFEST
                .iter()
                .map(|(n, _)| *n)
                .filter(|n| !seen.insert(*n))
                .collect::<Vec<_>>()
        }
    );

    let unaccounted: Vec<&String> = on_disk.difference(&manifest).collect();
    let stale: Vec<&String> = manifest.difference(&on_disk).collect();

    assert!(
        unaccounted.is_empty(),
        "Unaccounted compartment-mapper fixtures (present on disk but missing from MANIFEST): {unaccounted:?}.\n\
         Add each to MANIFEST in rust/endo/tests/compartment_mapper_fixture_parity.rs as either\n\
         Exercise {{ entry }} (the walker faithfully handles it; commit its expected-compartment-map.json),\n\
         PendingExclude {{ capability: \"…\" }} (name the walker capability group it is blocked on), or\n\
         DurableExclude {{ reason: \"…\" }} (a compartment-mapper-internal concern out of the walker's scope).\n\
         This drift guard exists so a newly added fixture cannot be silently ignored."
    );
    assert!(
        stale.is_empty(),
        "Stale MANIFEST entries (listed here but no such fixture directory on disk): {stale:?}.\n\
         Remove them from MANIFEST in rust/endo/tests/compartment_mapper_fixture_parity.rs."
    );
}

/// Every accounted exclusion carries a non-empty, human-readable
/// justification, so the safeguard cannot be defeated by a blank skip.
#[test]
fn every_exclusion_has_a_reason() {
    for (name, disp) in MANIFEST {
        match disp {
            PendingExclude { capability } => assert!(
                capability.len() >= 12,
                "pending exclusion for {name} needs a substantive capability, got: {capability:?}"
            ),
            DurableExclude { reason } => assert!(
                reason.len() >= 12,
                "durable exclusion for {name} needs a substantive reason, got: {reason:?}"
            ),
            Exercise { .. } => {}
        }
    }
}

/// Run the walker against every exercised fixture and diff its
/// compartment map, **structurally**, against the committed golden
/// generated by the node reference oracle
/// (`rust/endo/tools/gen-parity-golden.mjs`). This is the parity
/// surface that grows as the walker gains capabilities. Also enforces
/// the anti-backslide [`EXERCISED_FLOOR`].
/// The emulated harness inputs (condition set + host/exit modules) a
/// fixture is exercised with, supplied *identically* to endor's walker
/// here and to the node reference oracle in
/// `rust/endo/tools/gen-parity-golden.mjs` — the "emulate, don't
/// refactor" rule (`designs/endor-run-expanded.md` § Fixture-parity ratchet). Most
/// fixtures need none; the exceptions:
///
/// - `conditional-host-exports` emulates the `endo:lib` host condition
///   (selecting `lib`'s `exports["endo:lib"]`), which the fixture's own
///   harness passes.
/// - `fixtures-0` admits the entry package's `devDependencies` via the
///   `development` condition and declares `builtin` a host/exit module,
///   matching its `app.agar-make.js` harness options.
/// - `no-trans-dev-deps` explicitly uses `dev: false`, matching the node
///   oracle and proving an installed development-only dependency is not
///   admitted merely because source imports it.
/// - `dynamic-ancestor` enables the entry package's development dependencies,
///   matching the fixture's own dynamic-require harness.
/// - `language-for-extension` registers the `xsonp` → `jsonp` language via
///   the emulated `languageForExtension`, matching the fixture's own
///   `parserForLanguage: { jsonp }` / `languageForExtension: { xsonp: 'jsonp' }`
///   scaffold. `assets` needs no emulated option — `.text`/`.bytes` are
///   default languages and `.uint32` is classified by the entry package's own
///   `"parsers"` map.
/// - `exit` supplies `h2g2:meaning` as executable synthetic source through the
///   exit-module hook, matching the fixture's runtime import hook.
/// - `module-source-hook` supplies the undeclared transitive `dependency-b`
///   through that same exit seam and observes both the file and synthetic
///   sources through the module-source hook.
#[derive(Default)]
struct HookLogs {
    exit_module_imports: Arc<Mutex<Vec<String>>>,
    module_sources: Arc<Mutex<Vec<(String, String)>>>,
}

fn walk_options_for(name: &str) -> (WalkOptions, HookLogs) {
    let logs = HookLogs::default();
    let options = match name {
        "fixtures-conditional-host-exports" => {
            WalkOptions::new(["endo:lib".to_string()], std::iter::empty())
        }
        "fixtures-language-for-extension" => {
            let mut options = WalkOptions::default();
            options
                .language_for_extension
                .insert("xsonp".to_string(), "jsonp".to_string());
            options
        }
        // Emulate the fixture's `browser` condition, activating the browser
        // resolve field on both the node oracle and endor's walker.
        "fixtures-resolve" => WalkOptions::new(["browser".to_string()], std::iter::empty()),
        "fixtures-0" => WalkOptions::new(["development".to_string()], ["builtin".to_string()]),
        "fixtures-dynamic-ancestor" => {
            let mut options = WalkOptions::default();
            options.dev = true;
            options
        }
        "fixtures-common-deps" => {
            // Emulate the fixture's `commonDependencies` harness option:
            // the alias `unlisted-common-dep` resolves to the entry
            // package's `common-dep-target` dependency, available to every
            // package. Supplied identically to the node oracle.
            let mut options = WalkOptions::default();
            options.common_dependencies.insert(
                "unlisted-common-dep".to_string(),
                "common-dep-target".to_string(),
            );
            options
        }
        "fixtures-exit" => {
            let imports = Arc::clone(&logs.exit_module_imports);
            WalkOptions::default().with_exit_module_import_hook(move |request| {
                imports.lock().unwrap().push(request.specifier.to_string());
                Ok((request.specifier == "h2g2:meaning")
                    .then(|| SyntheticModuleSource::new("export const meaning = 42;")))
            })
        }
        "fixtures-module-source-hook" => {
            let imports = Arc::clone(&logs.exit_module_imports);
            let sources = Arc::clone(&logs.module_sources);
            WalkOptions::default()
                .with_exit_module_import_hook(move |request| {
                    imports.lock().unwrap().push(request.specifier.to_string());
                    Ok((request.specifier == "dependency-b").then(|| {
                        SyntheticModuleSource::new(
                            "export const value = 'dependency-b'; export default value;",
                        )
                    }))
                })
                .with_module_source_hook(move |module_source| {
                    let origin = match module_source.origin {
                        ModuleSourceOrigin::File { .. } => "file",
                        ModuleSourceOrigin::SyntheticExit { .. } => "synthetic",
                    };
                    sources
                        .lock()
                        .unwrap()
                        .push((origin.to_string(), module_source.specifier.to_string()));
                    Ok(())
                })
        }
        _ => WalkOptions::default(),
    };
    (options, logs)
}

#[test]
fn exercised_fixtures_match_node_golden() {
    let root = fixtures_root();
    let tmp = tempfile::tempdir().unwrap();

    let mut exercised = 0usize;
    for (name, disp) in MANIFEST {
        let Exercise { entry } = disp else {
            continue;
        };
        exercised += 1;

        let entry_path = root.join(name).join(entry);
        assert!(
            entry_path.is_file(),
            "{name}: exercised entry point {entry} does not exist at {}",
            entry_path.display()
        );

        let golden_path = root.join(name).join("expected-compartment-map.json");
        assert!(
            golden_path.is_file(),
            "{name}: missing golden at {}. Generate it with\n\
             `node rust/endo/tools/gen-parity-golden.mjs {}`.",
            golden_path.display(),
            name.strip_prefix("fixtures-").unwrap_or(name)
        );

        let cas = ContentStore::open(&tmp.path().join(name)).unwrap();
        let (options, hook_logs) = walk_options_for(name);
        let ingested = ingest_entry_point_with_deps_with_options(&cas, &entry_path, &options)
            .unwrap_or_else(|e| panic!("{name}: walker failed on {entry}: {e}"));

        let (projection, want, expected_hooks) = parse_golden(&golden_path);
        assert_eq!(
            *hook_logs.exit_module_imports.lock().unwrap(),
            expected_hooks.exit_module_imports,
            "{name}: exit-module hook observations differ from the node oracle"
        );
        assert_eq!(
            *hook_logs.module_sources.lock().unwrap(),
            expected_hooks.module_sources,
            "{name}: module-source hook observations differ from the node oracle"
        );

        let got = project_endor(&ingested.archive.map, projection);

        assert!(
            got.entry_compartment == want.entry_compartment
                && got.entry_module == want.entry_module
                && got.compartments == want.compartments,
            "{name}: walker output does not match the committed golden.\n\
             --- expected (golden: {}) ---\n{}\n--- actual (endor walker) ---\n{}\n\
             If the walker's behaviour changed on purpose, regenerate the golden with\n\
             `node rust/endo/tools/gen-parity-golden.mjs {}` (node-oracle fixtures) or update the\n\
             committed endor-baseline golden by hand (fixtures whose golden.oracle is \"endor-baseline\").",
            golden_path.display(),
            render(&want),
            render(&got),
            name.strip_prefix("fixtures-").unwrap_or(name),
        );

        if matches!(*name, "fixtures-exit" | "fixtures-module-source-hook") {
            xsnap::run_xs_archive_loaded(&ingested.archive).unwrap_or_else(|error| {
                panic!("{name}: emulated host source did not execute: {error}")
            });
        }
    }

    // Anti-backslide: the exercised set must never drop below the
    // ratcheting floor. A change that silently re-excludes a graduated
    // fixture trips this.
    assert!(
        exercised >= EXERCISED_FLOOR,
        "exercised fixtures ({exercised}) fell below the ratchet floor ({EXERCISED_FLOOR}); \
         a graduated fixture was re-excluded. Restore it, or (with maintainer sign-off) lower \
         EXERCISED_FLOOR — but backsliding the parity campaign should be deliberate, not silent."
    );
}

/// The parity scoreboard: prints `exercised / pending / durable` so
/// campaign progress is a visible number, and cross-checks the tallies
/// against the manifest size and the exercised floor.
#[test]
fn scoreboard() {
    let mut exercised = 0usize;
    let mut pending = 0usize;
    let mut durable = 0usize;
    for (_, disp) in MANIFEST {
        match disp {
            Exercise { .. } => exercised += 1,
            PendingExclude { .. } => pending += 1,
            DurableExclude { .. } => durable += 1,
        }
    }

    let total = MANIFEST.len();
    println!(
        "compartment-mapper fixture parity scoreboard: \
         {exercised} exercised / {pending} pending / {durable} durable  (of {total} fixtures)"
    );
    println!(
        "  campaign horizon: {} fixtures still to graduate (pending); \
         {durable} durably out of the walker's scope",
        pending
    );

    assert_eq!(
        exercised + pending + durable,
        total,
        "scoreboard tallies ({exercised}+{pending}+{durable}) do not sum to the manifest size ({total})"
    );
    assert!(
        exercised >= EXERCISED_FLOOR,
        "scoreboard: exercised ({exercised}) is below the ratchet floor ({EXERCISED_FLOOR})"
    );
}

/// `fixtures-no-name` proves the walker's unnamed-package handling:
/// the reexported dependency has no `name` field, so its compartment
/// id must fall back to the directory basename (`no-name-pkg`). This
/// is an endor *extension* over compartment-mapper, which rejects a
/// nameless package outright (its own test/no-name.test.js asserts the
/// throw) — hence the fixture's golden is an `endor-baseline`, not a
/// node-oracle map.
#[test]
fn no_name_fixture_uses_directory_basename_for_compartment_id() {
    let root = fixtures_root();
    let tmp = tempfile::tempdir().unwrap();
    let entry = root.join("fixtures-no-name/node_modules/app/index.js");

    let cas = ContentStore::open(tmp.path()).unwrap();
    let ingested = ingest_entry_point_with_deps(&cas, &entry).unwrap();

    assert!(
        ingested
            .archive
            .map
            .compartments
            .contains_key("no-name-pkg-v1.0.0"),
        "expected a compartment keyed by the unnamed package's directory basename; got {:?}",
        {
            let mut ids: Vec<_> = ingested.archive.map.compartments.keys().cloned().collect();
            ids.sort();
            ids
        }
    );
}
