#!/usr/bin/env python3
"""The release-neutral gate: the native probe at a base revision against the
working tree, byte for byte.

STACK-DEPTH-REFACTOR.md §5 Phase 1 lands refactors that must change no
program's outcome: not its halt, not its result, not one computron of its
meter or where the meter is checked, and for the compiler not one byte of
bytecode or one parse-meter charge. This script builds the native probe at a
base revision (extracted with `git archive`, cached by commit) and from the
working tree, hands both the same program text, and fails on any difference:

  corpus    every case of the working tree's `cases.rs`;
  families  every heavy family, walker and chain kind at depths around its
            recorded ceiling (0, 1, 2, half, ceiling - 1, ceiling, + 1, + 2),
            generated by the working tree's probe (`family-source`);
  snippets  the programs in `differential/*.js`, written per change to reach
            what the corpus does not (trap order, revocation mid-chain,
            invariant violations, metering order); a file holds several,
            separated by `// ---` lines, and a program's first line may be
            `// flags: --eval-compiler` and/or `--compile-only`.

Every run carries `--digest` (the compile's bytecode, symbols, raw parse
meter and the sequence of parse-meter charges) and `--meter-trace` (the meter
armed at every computron, with the count at each check it reaches), so a
meter check moved or added across a computron boundary differs even when the
total does not; the trace sees whole computrons, so a check moved within one
does not. A base build without them fails the gate unless `--allow-partial`
is given.

Verdicts: `same`; `differs`; `timeout` (either build, a failure); `error` (the
harness could not read a line); and `fixed`, for a program on which the base
build overflows the contract stack natively and the working tree completes,
which is not a difference but a repair.

  python3 differential.py                   # uncommitted work against HEAD
  python3 differential.py --base HEAD^      # the last commit against its parent
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import fcntl
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_probe  # noqa: E402
import ceilings  # noqa: E402
import common  # noqa: E402

REPO = common.ROOT.parents[1]
SNIPPETS = common.LANES / "differential"
CACHE = build_probe.PROBE / "target/differential"
SEPARATOR = "// ---"
FLAGS = "// flags:"
SNIPPET_FLAGS = ("--compile-only", "--eval-compiler")
COMPARED = ("--digest", "--meter-trace")


def resolve(rev):
    return subprocess.check_output(["git", "rev-parse", "--verify", f"{rev}^{{commit}}"], cwd=REPO,
                                   text=True).strip()


# What the probe is built from: a change elsewhere (a snippet, a list, a
# README) leaves both builds the same engine.
BUILD_INPUTS = (":(glob)rust/engine/**/*.rs", ":(glob)rust/engine/**/Cargo.toml",
                "rust/engine/Cargo.lock", "rust/engine/rust-toolchain.toml")


def changed_since(commit):
    """Whether the working tree's build inputs under `rust/engine` differ from
    `commit`, counting untracked files."""
    diff = subprocess.run(["git", "diff", "--quiet", commit, "--", *BUILD_INPUTS], cwd=REPO)
    if diff.returncode != 0:
        return True
    untracked = subprocess.check_output(["git", "ls-files", "--others", "--exclude-standard", "--",
                                         *BUILD_INPUTS], cwd=REPO, text=True)
    return bool(untracked.strip())


def base_probe(rev, quiet=True):
    """The native probe built at `rev`, from `git archive` of its `rust/engine`
    into a temporary directory outside the repository, cached by commit. The
    builds share one target directory so registry dependencies build once
    (each base's own crates build afresh, from a new path), and a lock keeps
    two runs from building or copying at once."""
    commit = resolve(rev)
    CACHE.mkdir(parents=True, exist_ok=True)
    binary = CACHE / f"ih-stack-probe-{commit[:12]}"
    with open(CACHE / "build.lock", "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if binary.exists():
            return binary, commit
        with tempfile.TemporaryDirectory(prefix="ih-differential-") as tree:
            archive = subprocess.Popen(["git", "archive", commit, "rust/engine"], cwd=REPO,
                                       stdout=subprocess.PIPE)
            untar = subprocess.run(["tar", "-x", "-f", "-", "-C", tree], stdin=archive.stdout)
            archive.stdout.close()
            if archive.wait() != 0 or untar.returncode != 0:
                raise SystemExit(f"git archive of {rev} failed")
            probe = Path(tree) / "rust/engine/stack-lanes/probe"
            if not (probe / "Cargo.toml").exists():
                raise SystemExit(f"{rev} has no stack-lanes probe to build")
            shutil.copyfile(Path(tree) / "rust/engine/Cargo.lock", probe / "Cargo.lock")
            env = dict(os.environ, CARGO_INCREMENTAL="0", CARGO_TARGET_DIR=str(CACHE / "target"))
            subprocess.run(["cargo", "build", "--release"] + (["--quiet"] if quiet else []), cwd=probe,
                           env=env, check=True)
        staging = binary.with_suffix(".tmp")
        shutil.copyfile(CACHE / "target/release/ih-stack-probe", staging)
        staging.chmod(0o755)
        os.replace(staging, binary)
    return binary, commit


def clean():
    """Drop the cached base binaries, their shared target directory, and
    anything an older version of this script left (nested worktrees)."""
    for tree in sorted(CACHE.glob("tree-*")):
        subprocess.run(["git", "worktree", "remove", "--force", str(tree)], cwd=REPO, check=False)
    subprocess.run(["git", "worktree", "prune"], cwd=REPO, check=False)
    for binary in CACHE.glob("ih-stack-probe-*"):
        binary.unlink()
    shutil.rmtree(CACHE / "target", ignore_errors=True)


# ---- inputs ----------------------------------------------------------------

def depths(ceiling):
    return sorted({d for d in (0, 1, 2, ceiling // 2, ceiling - 1, ceiling, ceiling + 1, ceiling + 2) if d >= 0})


class SnippetError(ValueError):
    pass


def parse_snippets(text, origin):
    """The programs of one snippet file: (name, source, flags). A program's
    flags line must be its first non-blank line and name only
    `--compile-only` and `--eval-compiler`."""
    text = text.lstrip("﻿")
    programs = []
    chunk = []

    def flush():
        lines = "\n".join(chunk).strip("\n").splitlines()
        if not any(line.strip() for line in lines):
            return
        name = f"{origin}#{len(programs) + 1}"
        flags = []
        first = next(i for i, line in enumerate(lines) if line.strip())
        if lines[first].strip().startswith(FLAGS):
            flags = lines[first].strip()[len(FLAGS):].split()
            unknown = [flag for flag in flags if flag not in SNIPPET_FLAGS]
            if unknown:
                raise SnippetError(f"{name}: unknown flags {unknown}; allowed: {list(SNIPPET_FLAGS)}")
        misplaced = [line for line in lines[first + 1:] if line.strip().startswith(FLAGS)]
        if misplaced:
            raise SnippetError(f"{name}: a flags line must be the program's first line")
        programs.append((name, "\n".join(lines) + "\n", flags))

    for line in text.splitlines():
        if line.strip() == SEPARATOR:
            flush()
            chunk = []
        else:
            chunk.append(line)
    flush()
    return programs


def source_flags(compile_only, eval_compiler):
    return (["--compile-only"] if compile_only else []) + (["--eval-compiler"] if eval_compiler else [])


def family_input(probe, kind, family, n):
    line = subprocess.check_output([str(probe), "family-source", kind, family, str(n)], text=True)
    generated = json.loads(line)
    return (f"{kind} {family} {n}", source_flags(generated["compile_only"], generated["eval_compiler"]),
            generated["source"])


def inputs(probe, include_slow, only, jobs):
    """(label, flags, source) for every comparison, all as program text."""
    work = []
    if only in (None, "corpus"):
        for case in common.dump_cases(probe):
            if not include_slow and case["name"] in common.SLOW_CASES:
                continue
            work.append((f"case {case['name']}", source_flags(not case["run"], case["eval_compiler"]),
                         case["source"]))
    if only in (None, "families"):
        requests = [(kind, family, n) for kind in ("heavy", "walker", "chain")
                    for family, ceiling in ceilings.recorded(kind) for n in depths(ceiling)]
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            work.extend(pool.map(lambda request: family_input(probe, *request), requests))
    if only in (None, "snippets"):
        for path in sorted(SNIPPETS.glob("*.js")):
            for name, source, flags in parse_snippets(path.read_text(encoding="utf-8-sig"), path.name):
                work.append((f"snippet {name}", flags, source))
    return work


# ---- comparison ------------------------------------------------------------

def supports(probe, flag, marker):
    """Whether a probe build honors a run flag (older ones ignore it)."""
    return marker in (common.run_native(probe, ["source", flag], stdin="1").line or "")


def outcome(probe, flags, source, timeout, compared):
    """What a run printed, as a comparable string: its outcome line, the
    trap, or `timeout`."""
    result = common.run_native(probe, ["source", *flags, *compared], stdin=source, timeout=timeout)
    if result.timed_out:
        return "timeout"
    if result.trapped:
        return f"trap: {result.trap}"
    return result.line


def classify(old, new):
    if "timeout" in (old, new):
        return "timeout"
    if old == new:
        return "same"
    overflowed = old.startswith("trap:") and any(marker in old for marker in common.NATIVE_TRAP)
    if overflowed and not new.startswith("trap:"):
        return "fixed"
    return "differs"


def compare(old_probe, new_probe, work, jobs, timeout, compared):
    def one(item):
        label, flags, source = item
        try:
            old = outcome(old_probe, flags, source, timeout, compared)
            new = outcome(new_probe, flags, source, timeout, compared)
        except common.HarnessError as error:
            return label, "error", str(error), ""
        return label, classify(old, new), old, new

    with ThreadPoolExecutor(max_workers=jobs) as pool:
        return list(pool.map(one, work))


FAILING = ("differs", "timeout", "error")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base", default="HEAD", help="the revision to compare against (default: HEAD)")
    parser.add_argument("--only", choices=("corpus", "families", "snippets"))
    parser.add_argument("--slow", action="store_true", help="include the slow cases")
    parser.add_argument("--jobs", type=int, default=os.cpu_count() or 2)
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument("--no-build", action="store_true", help="use the working tree's last native build")
    parser.add_argument("--allow-partial", action="store_true",
                        help="compare without the digest or meter trace a base build lacks")
    parser.add_argument("--allow-unchanged", action="store_true",
                        help="compare even when the working tree matches the base")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--clean", action="store_true", help="remove the cached base builds and exit")
    args = parser.parse_args()
    if args.clean:
        clean()
        return 0
    commit = resolve(args.base)
    if not args.allow_unchanged and not changed_since(commit):
        print(f"nothing to compare: rust/engine in the working tree matches {args.base} ({commit[:12]}); "
              f"compare a commit against its parent with --base <commit>^", file=sys.stderr)
        return 2
    old_probe, commit = base_probe(args.base)
    new_probe = build_probe.artifact() if args.no_build else build_probe.build(quiet=True)
    compared = []
    for flag, marker in (("--digest", "digest="), ("--meter-trace", "checks=")):
        if supports(old_probe, flag, marker):
            compared.append(flag)
        elif not args.allow_partial:
            print(f"the base build ({commit[:12]}) has no {flag}; rebase onto a revision that has it, "
                  f"or pass --allow-partial to compare without it", file=sys.stderr)
            return 2
    work = inputs(new_probe, args.slow, args.only, args.jobs)
    if not work:
        print("nothing to compare: no inputs", file=sys.stderr)
        return 2
    missing = [flag for flag in COMPARED if flag not in compared]
    print(f"comparing {len(work)} programs: {args.base} ({commit[:12]}) against the working tree"
          f"{' without ' + ' and '.join(missing) if missing else ''}", flush=True)
    results = compare(old_probe, new_probe, work, args.jobs, args.timeout, compared)
    counts = {}
    for label, verdict, old, new in results:
        counts[verdict] = counts.get(verdict, 0) + 1
        if verdict != "same":
            print(f"{verdict:8s} {label}\n  base: {old}\n  new:  {new}")
    print("differential: " + ", ".join(f"{n} {v}" for v, n in sorted(counts.items())))
    if args.output:
        common.write_json(args.output, {"base": commit, "compared": compared, "results": [
            {"input": label, "verdict": verdict, "base": old, "new": new} for label, verdict, old, new in results]})
    return 1 if any(counts.get(verdict) for verdict in FAILING) else 0


if __name__ == "__main__":
    sys.exit(main())
