export type * from './types.js';
export type {
  DirEntry,
  FsBackend,
  NodeKind,
  WatchEvent,
} from './backend-types.js';
export {
  bind,
  BlobRefInterface,
  cacheBackedRead,
  chroot,
  collectBytes,
  collectStream,
  compose,
  CursorInterface,
  DirectoryInterface,
  emptyFilesystem,
  FileInterface,
  FilesystemInterface,
  LayerInterface,
  LockInterface,
  makeFromMountBackend,
  makeInMemoryBackend,
  makeInMemoryFilesystem,
  makeLayer,
  makeMemoryCas,
  makeNodeFilesystem,
  makeNodeFsBackend,
  mountAsFilesystem,
  namespace,
  NodeWatcherInterface,
  OpenFileInterface,
  PassableBytesReaderInterface,
  PassableBytesWriterInterface,
  PassableReaderInterface,
  PosixFsInterface,
  readOnly,
  walk,
  withCachedReads,
  wrapBackend,
  XattrsInterface,
} from './index.js';
