// @ts-check

import test from 'ava';

import { makeXorShift } from '../index.js';

const seedA = /** @type {[number, number, number, number]} */ ([
  0xb0b5c0ff, 0xeefacade, 0xb0b5c0ff, 0xeefacade,
]);
const seedB = /** @type {[number, number, number, number]} */ ([
  0x12345678, 0x9abcdef0, 0x0fedcba9, 0x87654321,
]);

test('determinism: same seed produces same sequence', t => {
  const a = makeXorShift([...seedA]);
  const b = makeXorShift([...seedA]);
  for (let i = 0; i < 32; i += 1) {
    t.is(a.random(), b.random(), `mismatch at index ${i}`);
  }
});

test('different seeds produce different sequences', t => {
  const a = makeXorShift([...seedA]);
  const b = makeXorShift([...seedB]);
  // Compare the first 8 outputs; with 64-bit state and unrelated seeds,
  // a collision in the first 8 is astronomically unlikely.
  let differs = false;
  for (let i = 0; i < 8; i += 1) {
    if (a.random() !== b.random()) {
      differs = true;
    }
  }
  t.true(differs);
});

test('random() yields values in [0, 1)', t => {
  const prng = makeXorShift([...seedA]);
  for (let i = 0; i < 1000; i += 1) {
    const x = prng.random();
    t.true(Number.isFinite(x), 'finite');
    t.true(x >= 0, `x >= 0 (got ${x})`);
    t.true(x < 1, `x < 1 (got ${x})`);
  }
});

test('randomint() returns a pair of non-negative 32-bit integers', t => {
  const prng = makeXorShift([...seedA]);
  for (let i = 0; i < 1000; i += 1) {
    const pair = prng.randomint();
    t.is(pair.length, 2);
    const [hi, lo] = pair;
    t.true(Number.isInteger(hi), `hi integer (got ${hi})`);
    t.true(Number.isInteger(lo), `lo integer (got ${lo})`);
    t.true(hi >= 0 && hi <= 0xffffffff, `hi in u32 range (got ${hi})`);
    t.true(lo >= 0 && lo <= 0xffffffff, `lo in u32 range (got ${lo})`);
  }
});

test('mean of 10000 random() samples is close to 0.5', t => {
  const prng = makeXorShift([...seedA]);
  const n = 10000;
  let sum = 0;
  for (let i = 0; i < n; i += 1) {
    sum += prng.random();
  }
  const mean = sum / n;
  // Generous slack: a true uniform mean over 10000 samples has stddev
  // ~ sqrt(1/12) / sqrt(10000) ~= 0.00289.  0.05 is ~17 sigma.
  t.true(Math.abs(mean - 0.5) < 0.05, `mean=${mean}`);
});

test('returned generator is frozen', t => {
  const prng = makeXorShift([...seedA]);
  t.true(Object.isFrozen(prng));
  t.throws(() => {
    /** @type {any} */ (prng).random = () => 0;
  });
});

test('throws TypeError on bad seed', t => {
  const bad = /** @type {any} */ (undefined);
  t.throws(() => makeXorShift(bad), { instanceOf: TypeError });
  t.throws(() => makeXorShift(/** @type {any} */ ([1, 2, 3])), {
    instanceOf: TypeError,
  });
  t.throws(() => makeXorShift(/** @type {any} */ ('not an array')), {
    instanceOf: TypeError,
  });
});

test('throws TypeError on the all-zero seed (degenerate fixed point)', t => {
  t.throws(() => makeXorShift([0, 0, 0, 0]), { instanceOf: TypeError });
});

test('two instances are independent', t => {
  const a = makeXorShift([...seedA]);
  const b = makeXorShift([...seedA]);
  const fromA = [a.random(), a.random(), a.random()];
  // Consuming b should not affect a's subsequent outputs.
  b.random();
  b.random();
  const moreFromA = [a.random(), a.random()];
  const fresh = makeXorShift([...seedA]);
  const expected = [
    fresh.random(),
    fresh.random(),
    fresh.random(),
    fresh.random(),
    fresh.random(),
  ];
  t.deepEqual([...fromA, ...moreFromA], expected);
});

// Pinned regression vector: refactors that silently change the PRNG output
// would invalidate downstream fuzz traces.  Generated by running
// makeXorShift(seedA).randomint() eight times and capturing the [hi, lo] pairs
// as unsigned 32-bit integers.
test('regression vector for seedA pins the first eight randomint() outputs', t => {
  const prng = makeXorShift([...seedA]);
  /** @type {Array<[number, number]>} */
  const expected = [
    [1634435583, 3723859388],
    [724083122, 772555014],
    [827775663, 3213299041],
    [1193115869, 2648350373],
    [1825907402, 253445823],
    [384034626, 3388777071],
    [1312919365, 1859542134],
    [2570848256, 1425516919],
  ];
  for (let i = 0; i < expected.length; i += 1) {
    const [hi, lo] = prng.randomint();
    t.is(hi, expected[i][0], `hi at ${i}`);
    t.is(lo, expected[i][1], `lo at ${i}`);
  }
});
