#!/usr/bin/env python3
"""Generate the compiler's opcode constants and widths from the VM table."""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ironhorse-vm/src/opcode.rs"
TARGET = ROOT / "ironhorse-compile/src/opcodes.rs"


def generate(source):
    enum = source.split("pub enum Opcode {", 1)[1].split("}", 1)[0]
    entries = re.findall(r"^\s+(XS_\w+) = (\d+),$", enum, re.MULTILINE)
    count = int(re.search(r"pub const XS_CODE_COUNT: usize = (\d+);", source)[1])
    if [int(value) for _, value in entries] != list(range(count)):
        raise ValueError("VM opcode enum is not dense or count disagrees")
    id_size = int(re.search(r"pub const ID_SIZE: usize = (\d+);", source)[1])
    sizes = source.split("pub static CODE_SIZES:", 1)[1].split("];", 1)[0]
    widths = re.findall(r"^\s+(-?\d+),\s*// (XS_\w+)$", sizes, re.MULTILINE)
    if [name for _, name in widths] != [name for name, _ in entries]:
        raise ValueError("VM size table does not match enum order")
    lines = [
        "//! Generated by scripts/generate-compiler-opcodes.py from the VM opcode table.",
        "//! Run that script after changing ironhorse-vm/src/opcode.rs; CI checks drift.",
        "//! Width-selecting _1/_2/_4 families retain the VM's contiguous ordinals.",
        "#![allow(dead_code)]", "",
    ]
    lines += [f"pub const {name}: i32 = {value};" for name, value in entries]
    lines += ["", f"pub const XS_CODE_COUNT: usize = {count};",
              f"pub const ID_SIZE: i32 = {id_size};", "",
              "pub const OPCODE_NAMES: [&str; XS_CODE_COUNT] = ["]
    lines += [f'    "{name}",' for name, _ in entries]
    lines += ["];", "", "/// VM size sentinels: 0 is an ID; -1/-2/-4 carry a length prefix.",
              "#[rustfmt::skip]",
              "pub const CODE_SIZES: [i8; XS_CODE_COUNT] = ["]
    lines += [f"    {value}, // {name}" for value, name in widths]
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate(SOURCE.read_text())
    if args.check:
        if TARGET.read_text() != result:
            print(f"{TARGET}: regenerate with {pathlib.Path(__file__).name}", file=sys.stderr)
            return 1
    else:
        TARGET.write_text(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
