#!/usr/bin/env python3
"""Generate/check the locked ICU data profile (Python 3.11+).

Supported releases use the checked lockfiles and bundled ICU data. Custom data
builds are outside this profile. The fixed baseline alias preserves pre-existing
snapshots; NEVER move the baseline when upgrading dependencies.
"""
import hashlib
import json
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUTPUT = REPO / "rust/engine/ironhorse-vm/src/intl_profile.rs"
BASELINE = "8c77b93d00a20b90d248b50a25a3ee4f662cb83e55981a3633a37472defdd33c"


def fingerprint(packages, dependencies):
    roots = {name: spec for name, spec in dependencies.items() if name.startswith("icu_")}
    if not {"icu_normalizer", "icu_segmenter"} <= roots.keys():
        raise ValueError("Expected ICU normalization and segmentation dependencies")
    vm = next(p for p in packages if p["name"] == "ironhorse-vm")
    pending = [d for d in vm["dependencies"] if d.split()[0] in roots]
    if {d.split()[0] for d in pending} != roots.keys():
        raise ValueError("VM manifest and lockfile ICU roots disagree")
    records = {}
    while pending:
        dependency = pending.pop()
        parts = dependency.split(" ", 2)
        matches = [p for p in packages if p["name"] == parts[0]
                   and (len(parts) < 2 or p["version"] == parts[1])
                   and (len(parts) < 3 or f"({p.get('source', '')})" == parts[2])]
        if len(matches) != 1:
            raise ValueError(f"Missing or ambiguous dependency: {dependency}")
        package = matches[0]
        key = (package["name"], package["version"], package.get("source", ""))
        if key in records:
            continue
        if not package.get("checksum"):
            raise ValueError(f"ICU profile requires checksummed registry sources: {key}")
        children = sorted(package.get("dependencies", []))
        records[key] = [*key, package["checksum"], children]
        pending.extend(children)
    canonical = json.dumps([roots, sorted(records.values())], sort_keys=True,
                           separators=(",", ":")).encode()
    return hashlib.sha256(canonical).hexdigest()


def identity(digest):
    # This alias denotes one immutable dependency graph, not the latest graph.
    return "ironhorse-intl-2026a" if digest == BASELINE else f"ironhorse-intl-2026a:{digest}"


def rendered(digest):
    return ("// Generated by scripts/intl-profile.py --write; do not edit.\n"
            "// Locked ICU dependency graph (versions, checksums, edges and root features).\n"
            f"// SHA-256: {digest}\n"
            f'pub(crate) const INTL_DATA_VERSION: &str = "{identity(digest)}";\n')


def main():
    try:
        manifest = tomllib.loads((REPO / "rust/engine/ironhorse-vm/Cargo.toml").read_text())
        digests = [fingerprint(tomllib.loads((REPO / path).read_text())["package"],
                               manifest["dependencies"])
                   for path in ("Cargo.lock", "rust/engine/Cargo.lock")]
        if digests[0] != digests[1]:
            raise ValueError("Root and engine ICU dependency graphs disagree")
        content = rendered(digests[0])
        if sys.argv[1:] == ["--write"]:
            OUTPUT.write_text(content)
        elif sys.argv[1:]:
            raise ValueError("Usage: intl-profile.py [--write]")
        elif not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise ValueError("ICU identity is stale; run intl-profile.py --write and review snapshot compatibility")
        print(f"ICU profile: {identity(digests[0])} ({digests[0]})")
    except (OSError, KeyError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
