//! Cross-version semantic migrations for snapshots whose container schema is
//! still current but whose VM layout predates a language-correctness fix.
//!
//! `compat-8047.container` was produced by exact commit `8047fd52f` from:
//!
//! ```js
//! function capture() { return arguments; }
//! var held = capture(1, 2);
//! var seed = 1;
//! seed
//! ```
//!
//! That revision neither installed the implicit `Array.prototype.join`
//! dependency nor used the current arguments-object representation. Keeping
//! the producer bytes frozen is essential: a fixture generated by current code
//! can only prove same-version resume.

use ironhorse_snapshot::machine::from_snapshot_bytes;
use ironhorse_snapshot::Signature;
use ironhorse_vm::parse_symbols;

fn signature() -> Signature {
    Signature::new("ironhorse-worker-v1")
}

fn fixture() -> Vec<u8> {
    std::fs::read(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/compat-8047.container"),
    )
    .expect("read the exact-8047 fixture")
}

#[test]
fn old_container_gains_join_and_current_arguments_layout() {
    let mut machine = from_snapshot_bytes(&fixture(), &signature()).expect("restore old container");
    let source = "var held; var seed; \
                  var joined = '' + [seed, seed + 1]; \
                  joined + '|' + \
                    (Object.getPrototypeOf(held) === Object.prototype) + '|' + \
                    Object.prototype.hasOwnProperty.call(held, Symbol.iterator) + '|' + \
                    (held[Symbol.iterator] === Array.prototype.values) + '|' + \
                    Array.from(held).join(':')";
    let (bytecode, symbols) =
        ironhorse_compile::compile_atoms(source).expect("observation compiles");
    let names = parse_symbols(&symbols);
    let bytecode = machine
        .relink_crank(&bytecode, &names)
        .expect("observation relinks");
    let outcome = machine.run(&bytecode);

    assert!(outcome.completed, "observation crank: {:?}", outcome.halt);
    assert_eq!(outcome.result, "1,2|true|true|true|1:2");
}
