//! Cross-version semantic migrations for snapshots whose container schema is
//! still current but whose VM layout predates a language-correctness fix.
//!
//! `compat-8047.container` was produced by exact commit `8047fd52f` from:
//!
//! ```js
//! function capture() { return arguments; }
//! var held = capture(1, 2);
//! var seed = 1;
//! seed
//! ```
//!
//! That revision neither installed the implicit `Array.prototype.join`
//! dependency nor used the current arguments-object representation. Keeping
//! the producer bytes frozen is essential: a fixture generated by current code
//! can only prove same-version resume.
//!
//! `compat-8047-multi-arguments.container` comes from that same revision with
//! three live arguments objects. `compat-a50-custom-arguments.container` was
//! produced by exact commit `a50bc6e21` after selecting `Array.prototype` for
//! an arguments object and deleting its own `@@iterator`.

use ironhorse_snapshot::image::read_machine;
use ironhorse_snapshot::machine::{from_snapshot_bytes, MachineSnapshot};
use ironhorse_snapshot::Signature;
use ironhorse_vm::parse_symbols;

fn signature() -> Signature {
    Signature::new("ironhorse-worker-v1")
}

fn fixture(name: &str) -> Vec<u8> {
    std::fs::read(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name),
    )
    .expect("read the frozen cross-version fixture")
}

#[test]
fn old_container_gains_join_and_current_arguments_layout() {
    let mut machine = from_snapshot_bytes(&fixture("compat-8047.container"), &signature())
        .expect("restore old container");
    let source = "var held; var seed; \
                  var joined = '' + [seed, seed + 1]; \
                  joined + '|' + \
                    (Object.getPrototypeOf(held) === Object.prototype) + '|' + \
                    Object.prototype.hasOwnProperty.call(held, Symbol.iterator) + '|' + \
                    (held[Symbol.iterator] === Array.prototype.values) + '|' + \
                    Array.from(held).join(':')";
    let (bytecode, symbols) =
        ironhorse_compile::compile_atoms(source).expect("observation compiles");
    let names = parse_symbols(&symbols);
    let bytecode = machine
        .relink_crank(&bytecode, &names)
        .expect("observation relinks");
    let outcome = machine.run(&bytecode);

    assert!(outcome.completed, "observation crank: {:?}", outcome.halt);
    assert_eq!(outcome.result, "1,2|true|true|true|1:2");
}

#[test]
fn intermediate_container_preserves_guest_arguments_edits() {
    let mut machine = from_snapshot_bytes(
        &fixture("compat-a50-custom-arguments.container"),
        &signature(),
    )
    .expect("restore intermediate container");
    let source = "var held; var seed; \
                  (Object.getPrototypeOf(held) === Array.prototype) + '|' + \
                    Object.prototype.hasOwnProperty.call(held, Symbol.iterator) + '|' + seed";
    let (bytecode, symbols) =
        ironhorse_compile::compile_atoms(source).expect("observation compiles");
    let names = parse_symbols(&symbols);
    let bytecode = machine
        .relink_crank(&bytecode, &names)
        .expect("observation relinks");
    let outcome = machine.run(&bytecode);

    assert!(outcome.completed, "observation crank: {:?}", outcome.halt);
    assert_eq!(outcome.result, "true|false|1");
}

#[test]
fn multi_arguments_migration_is_byte_deterministic() {
    let old = fixture("compat-8047-multi-arguments.container");
    let old_image = read_machine(&old, &signature()).expect("decode old container");
    assert_eq!(old_image.arguments_brands.len(), 3, "fixture coverage");
    let mut canonical = None;
    for _ in 0..32 {
        let machine = from_snapshot_bytes(&old, &signature()).expect("restore old container");
        let migrated = machine
            .write_snapshot(&signature())
            .expect("write migrated snapshot");
        if let Some(expected) = &canonical {
            assert_eq!(&migrated, expected, "migration bytes vary between restores");
        } else {
            canonical = Some(migrated);
        }
    }
}
