import type {
  EndoGuestAuthority,
  GitRemoteProvision,
} from '@endo/daemon/provision.js';
import type { EndoGuest, NameOrPath } from '@endo/daemon';

import type { CodeModeGlobal } from '@endo/agent-tools/code-mode/types.js';

export type EndoCodeModeGitAccess = 'readOnly' | 'readWrite' | 'historyRewrite';

export type EndoCodeModeMount = {
  path: string;
  mode: 'readOnly' | 'readWrite';
  deniedSegments?: string[];
};

export type EndoCodeModeGit = {
  mount: string;
  path: string[];
  mode: EndoCodeModeGitAccess;
};

export type EndoCodeModeGitRemote = GitRemoteProvision;

export type EndoCodeModeProvisionSpec = {
  /** Object keys become guest filesystem binding names. */
  mount?: { [guestBinding: string]: EndoCodeModeMount };
  /** Object keys become guest Git binding names. */
  git?: { [guestBinding: string]: EndoCodeModeGit };
  /** Object keys become guest GitRemote binding names. */
  gitRemote?: { [guestBinding: string]: EndoCodeModeGitRemote };
  /** Existing Endo host-name to guest-name introductions. */
  introducedNames?: Record<string, string>;
  /** Keep Pi's standard tools alongside the Endo evaluator. */
  piTools?: 'preserve';
};

export type EndoCodeModeProvisionPersistence = {
  version: 4;
  /** Opaque retained guest pet name generated by the adapter. */
  guestName: string;
};

/** Internal, ephemeral request. Never store this in caller session state. */
export type EndoCodeModeProvisionRequest = {
  persistence: EndoCodeModeProvisionPersistence;
  authority: EndoGuestAuthority;
  introducedNames: Record<string, string>;
};

export type EndoCodeModeProvisionForkOptions = {
  forkFrom?: EndoCodeModeProvisionPersistence;
};

export type NormalizeEndoCodeModeProvisionOptions = {
  harness: string;
  sessionId: string;
  cwd: string;
};

export type EndoCodeModeConnectionFailureContext = {
  kind: 'disconnect' | 'protocol';
};

export type EndoCodeModeConnectionFailureObserver = (
  error: unknown,
  context: EndoCodeModeConnectionFailureContext,
) => void;

export type EndoCodeModeConnectionOptions = {
  sockPath?: string;
  onConnectionFailure?: EndoCodeModeConnectionFailureObserver;
};

export type ProvisionEndoCodeModeOptions =
  NormalizeEndoCodeModeProvisionOptions &
    EndoCodeModeConnectionOptions & {
      spec?: EndoCodeModeProvisionSpec;
    };

export type ReconstructEndoCodeModeOptions = EndoCodeModeConnectionOptions &
  EndoCodeModeProvisionForkOptions & {
    persistence: EndoCodeModeProvisionPersistence;
  };

export type EndoCodeModeProvisionResult = {
  guest: EndoGuest;
  globals: CodeModeGlobal[];
  persistence: EndoCodeModeProvisionPersistence;
  cleanup: () => Promise<void>;
};

/** Internal convenience for host adapters. */
export type EndoCodeModeGuestName = NameOrPath;

// Internal aliases keep the Pi adapter implementation compact. They are not
// re-exported by the package's public type index.
export type EndoProvisionSpec = EndoCodeModeProvisionSpec;
export type EndoProvisionPersistence = EndoCodeModeProvisionPersistence;
export type EndoProvisionForkOptions = EndoCodeModeProvisionForkOptions;
export type EndoProvisionResult = EndoCodeModeProvisionResult;
export type EndoProvisionRequest = EndoCodeModeProvisionRequest;
export type EndoConnectionFailureContext = EndoCodeModeConnectionFailureContext;
export type EndoConnectionFailureObserver =
  EndoCodeModeConnectionFailureObserver;
export type NormalizeEndoProvisionOptions =
  NormalizeEndoCodeModeProvisionOptions;
